WarfareList:
    FULL:
        - MODULARWARFARE_MWSWEAPON_N45
        - MODULARWARFARE_MWSWEAPON_SMG45
        - MODULARWARFARE_MWSWEAPON_MP40
        - MODULARWARFARE_MWSWEAPON_PDW251
        - MODULARWARFARE_MWSWEAPON_MP5SD
        - MODULARWARFARE_MWSWEAPON_PDW27
        - MODULARWARFARE_MWSWEAPON_P50
        - MODULARWARFARE_MWSWEAPON_UZI
    SEMI:
        - MODULARWARFARE_MWSWEAPON_FNX45
        - MODULARWARFARE_MWSWEAPON_P88
        - MODULARWARFARE_MWSWEAPON_REP701
        - MODULARWARFARE_MWSWEAPON_REP701A1
FiremodeNBT:
    FULL: "CAAAAARmdWxs\r\n"
    SEMI: "CAAAAARzZW1p\r\n"
